### PR TITLE
Portuguese (Brazil) translation + recipe fixes

### PR DESCRIPTION
**Pull request by vico93**
Partially based on vanilla's pt-br locale, and with a little bit of "artistic license" on some terms.

### CODE REVIEW

**Comment by vico93** [comment]
I think i will redo the PR because it actually merged two commits that i felt need to be separate PRs. Sorry for that.

**Comment by vico93** [comment]
Ah, sorry, dont know how to separate it. Will change the title to reflect the new context.

**Comment by skniro** [comment]
I think you should put fabric tags, lang files and recipes to resources path,not generated path.Because generated path's file all generation by fabric datagen. If you can change my datagen to tweaks recipes is better.

**Comment by skniro** [comment]
Just curious,why you want use shaped recipes not shapless recipes.

**Comment by skniro** [comment]
chocolatebar  jelly oreo rawmarshmallow sugarcube trailmix 's recipes change i need a reason. 
chocolatemilkbottle I agree this change but i don't want use shaped recipes in this.
Other change is approved.

**Comment by vico93** [comment]
> I think you should put fabric tags, lang files and recipes to resources path,not generated path.Because generated path's file all generation by fabric datagen. If you can change my datagen to tweaks recipes is better.

Ah, sorry, i'm not much familiarized with Fabric project structure, i found the corresponding files in `generated` so i thought it was the right place for them.

**Comment by vico93** [comment]
> Just curious,why you want use shaped recipes not shapless recipes.

In what recipes?

**Comment by vico93** [comment]
> chocolatebar jelly oreo rawmarshmallow sugarcube trailmix 's recipes change i need a reason. chocolatemilkbottle I agree this change but i don't want use shaped recipes in this. Other change is approved.

- I tweaked chocolate bar recipe to not clash with chocolate milk one, since they originally used the very same recipes.
- The shape of the bar recipe i simply got inspired by the icon of the item (similar to how the stick recipe is made).
- I made raw marshmallow to use sugar cubes because the latter was basically useless in the original recipe set. And to add a little bit more variety in the mod. That's why i also nerfed the recipe for sugar cubes (honestly, the original was kinda pointless).
- For the trailmix recipe, what i got is that it was basically a mix of all seeds available on a bowl. What i did was just add the missing beetroot seed and did a facelift to make it more similar vanilla recipes. Can be different, but i liked it.

In general, not all recipes should be shapeless, because it can clash with recipes added by other mods or datapacks. Of course some simple ones or "straight-at-a-point" ones can be kept as shapeless, but the more ingredients the recipe has, its better for compatibility to make them shaped.

**Comment by skniro** [comment]
I still want not to change the chocolatebar jelly oreo rawmarshmallow's recipes,I want they can same with 1.8's version,  sugarcube and trailmix's change I agree your mind,I will change it. And I will change it. I will finish it and merge it if you want continue the discussion, you can make a new issue or pull request.Finally,very thanks you like this mod and can do this.

**Comment by skniro** [comment]
I will change sugarcube need sugar size is 2,only 1 sugar i worry will break compatibility.

**Pull request merged**
